services:
  # Discord Reputation Bot
  bot:
    build: .
    container_name: ${CONTAINER_NAME:-aidi-reputation-bot}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/app/data/data.db
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      # Named volume for SQLite database persistence
      - bot_data:/app/data
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'
    # Security options (distroless already runs as non-root)
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

volumes:
  # SQLite database storage
  bot_data:
    driver: local
